name: Scrape Movie Showtimes (TMDB/Letterboxd Focused)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs every day at 15:00 UTC (00:00 JST next day)
    - cron: '0 15 * * *'

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "Google Chrome version:"
          google-chrome --version

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION_FULL_STRING=$(google-chrome --version)
          echo "Full Chrome Version String: $CHROME_VERSION_FULL_STRING"
          CHROME_VERSION_NUMBER=$(echo "$CHROME_VERSION_FULL_STRING" | awk '{print $3}')
          echo "Detected Chrome Version Number: $CHROME_VERSION_NUMBER"
          
          # Use the Chrome for Testing JSON endpoints to get the correct ChromeDriver URL
          CHROMEDRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" | jq -r --arg version "$CHROME_VERSION_NUMBER" '.versions[] | select(.version==$version) | .downloads.chromedriver[] | select(.platform=="linux64") | .url' | head -n 1)

          if [ -z "$CHROMEDRIVER_URL" ]; then
            echo "Could not find exact match ChromeDriver for Chrome $CHROME_VERSION_NUMBER. Trying to find closest match by major version."
            CHROME_MAJOR_VERSION=$(echo "$CHROME_VERSION_NUMBER" | cut -d. -f1)
            CHROMEDRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r --arg major_version "$CHROME_MAJOR_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64" and (.url | contains($major_version))) | .url' | head -n1 )
          fi
          
          if [ -z "$CHROMEDRIVER_URL" ]; then
            echo "ERROR: Failed to determine ChromeDriver download URL. Exiting."
            exit 1
          fi

          echo "Using ChromeDriver URL: $CHROMEDRIVER_URL"
          wget -O chromedriver_linux64.zip "$CHROMEDRIVER_URL"
          unzip chromedriver_linux64.zip -d ./chromedriver_temp
          
          if [ -f ./chromedriver_temp/chromedriver-linux64/chromedriver ]; then
            sudo mv ./chromedriver_temp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          elif [ -f ./chromedriver_temp/chromedriver ]; then
            sudo mv ./chromedriver_temp/chromedriver /usr/local/bin/chromedriver
          else
            echo "ERROR: chromedriver executable not found in expected path within zip."
            ls -R ./chromedriver_temp 
            exit 1
          fi
          sudo chmod +x /usr/local/bin/chromedriver
          rm -rf chromedriver_linux64.zip ./chromedriver_temp
          echo "ChromeDriver version installed:"
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          # Ensure 'requests' is in requirements.txt for TMDB API calls.
          # 'BeautifulSoup4' might not be strictly needed by main_scraper2.py anymore if Eiga.com HTML parsing is gone,
          # but individual cinema scrapers might still use it. Keep it if unsure.

      - name: Run scraper script
        run: python main_scraper2.py
        env:
          # IMPORTANT: Add your TMDB_API_KEY as a secret in your GitHub repository
          # Go to your repository > Settings > Secrets and variables > Actions > New repository secret
          # Name the secret TMDB_API_KEY and paste your key as the value.
          # The Python script is set up to read this environment variable if TMDB_API_KEY constant is not hardcoded
          # OR ensure the key is hardcoded in main_scraper2.py as you requested earlier.
          # If hardcoded, this env var here isn't strictly needed by the script, but it's good practice for future.
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }} 

      - name: Commit and push generated files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Add all relevant output files
          git add showtimes.json 
          git add tmdb_cache.json # Add the TMDB cache file
          # git add eiga_cache.json # Remove this if you're no longer generating/using eiga_cache.json

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of showtimes and cache files"
            git push
            echo "Generated files committed and pushed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
