name: Scrape Movie Showtimes

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs every day at 15:00 UTC (which is 00:00 JST the next day)
    # Adjust as needed. https://crontab.guru/ can help.
    - cron: '0 15 * * *'

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "Google Chrome version:"
          google-chrome --version

      # Note: ChromeDriver installation is handled by webdriver-manager in Python

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Ensure this file includes google-generativeai

      - name: Run scraper script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Make API key available
        run: python main_scraper.py

      - name: Commit and push showtimes.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add showtimes.json
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to showtimes.json to commit."
          else
            git commit -m "Automated update of showtimes.json (with English titles)"
            git push
            echo "showtimes.json committed and pushed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
